In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df = pd.read_csv("train.csv")
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [21]:
new_df = df.sample(30000)

In [22]:
new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       1
is_duplicate    0
dtype: int64

In [23]:
new_df.duplicated().sum()

np.int64(0)

In [24]:
ques_df = df[['question1', 'question2']]
ques_df.head()

,question1,question2
0,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...
1,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...
2,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...
3,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...
4,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

new_df = new_df.dropna()

ques_df = new_df[['question1', 'question2']]

cv = CountVectorizer(max_features=3000)

all_que = pd.concat([ques_df['question1'], ques_df['question2']])
cv.fit(all_que)

q1_arr = cv.transform(ques_df['question1']).toarray()
q2_arr = cv.transform(ques_df['question2']).toarray()

In [31]:
temp_df1 = pd.DataFrame(q1_arr, index= ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index= ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis=1)
temp_df.shape

(29999, 6000)

In [32]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
51157,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42221,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
333400,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
121083,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
228053,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180014,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
132716,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
303958,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
290774,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
154096,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
temp_df['is_duplicate'] = new_df['is_duplicate']

In [34]:
temp_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
51157,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42221,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
333400,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
121083,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
228053,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
from sklearn.model_selection import train_test_split

In [38]:
X = temp_df.values
y = temp_df['is_duplicate'].values

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [41]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test, y_pred)

0.9985

In [44]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_test)
accuracy_score(y_test, y_pred)

1.0